[package]
name = "hydra-dx-math"
version = "0.1.0"
authors = ['GalacticCouncil']
edition = "2018"

[dependencies]
primitive-types = {default-features = false, version = '0.9.0'}

[features]
default = ["std"]
std = []
